microservices:
  api:
    url: "http://localhost:3001"
    port: "3001"
    swaggerEnable: true
    database:
      type: postgres
      host: localhost
      port: 5432
      username: postgres
      password: L(/;-?"vjnSw+4,J5gVM)W
      database: postgres

  booking:
    url: "http://localhost:3002"
    port: "3002"
    # database:
    #   type: postgres
    #   host: localhost
    #   port: 5432
    #   username: postgres
    #   password: L(/;-?"vjnSw+4,J5gVM)W
    #   database: postgres
