microservices:
  bookingApi:
    url: 'http://localhost:3001'
    port: '3001'
    swaggerEnable: true
    database:
      type: postgres
      host: localhost
      port: 5432
      username: postgres
      password: L(/;-?"vjnSw+4,J5gVM)W
      database: postgres
    kafka:
      clientId: booking-api
      brokers: ['localhost:9092']

  bookingWorker:
    url: 'http://localhost:3002'
    port: '3002'
    database:
      type: postgres
      host: localhost
      port: 5432
      username: postgres
      password: L(/;-?"vjnSw+4,J5gVM)W
      database: postgres
    kafka:
      clientId: booking-worker
      brokers: ['localhost:9092']
queue:
  host: localhost
  port: 6379
  password: y.7uH,DB8Rgt;(>FQE?KxL
